### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by lucasvannoort** [JoaoCarabetta/deckgl2plotly#2]
Hello,

I have a problem when i try to launch your project.

I installed using `pipenv install` and everything went fine. But when I execute `usage.py` I get the following:

```
Running on http://127.0.0.1:8081/
Debugger PIN: 808-349-634
 * Serving Flask app "usage" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "usage.py", line 69, in <module>
    app.run_server(debug=True, port=8081)
  File "/home/lucasvn/.local/share/virtualenvs/deckgl2plotly-d-RWD455/lib/python3.7/site-packages/dash/dash.py", line 1492, in run_server
    **flask_run_options)
  File "/home/lucasvn/.local/share/virtualenvs/deckgl2plotly-d-RWD455/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/home/lucasvn/.local/share/virtualenvs/deckgl2plotly-d-RWD455/lib/python3.7/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/home/lucasvn/.local/share/virtualenvs/deckgl2plotly-d-RWD455/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/home/lucasvn/.local/share/virtualenvs/deckgl2plotly-d-RWD455/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/home/lucasvn/anaconda3/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/lucasvn/anaconda3/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/lucasvn/anaconda3/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/mnt/d/Lucas_VN/Project/Python/deckgl2plotly/usage.py'
```

Help, please :)

**Comment by JoaoCarabetta** [comment]
Hey @lucasvannoort,

I just built this project to test a concept, so this library is far from stable and mantained.

Since it's been a while that I last used it, I'm not able to remember how to make this work. If I were you, I'd start from scratch and compile it following the instructions at the README. Or maybe install it via pip https://pypi.org/project/deckglplotly/, but I cannot guarantee that it works.

Sorry

**Comment by lucasvannoort** [comment]
Thank @JoaoCarabetta for your reply.

I will try the different steps of your README or install it via pip ;)

Best regards
